# Generated by Django 3.2.10 on 2021-12-26 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('agent_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('email_institutionnel', models.EmailField(max_length=100, unique=True, verbose_name='Email Institutionnel')),
                ('sexe', models.CharField(choices=[('m', 'Masculin'), ('f', 'Féminin')], max_length=100, verbose_name='Sexe')),
                ('tel1', models.CharField(max_length=9, unique=True, verbose_name='Numéro Téléphone')),
                ('direction', models.CharField(choices=[('DAGE', 'DAGE'), ('DFPT', 'DFPT'), ('PEJA', 'PEJA'), ('CI', 'Cellule Informatique'), ('CG', 'Cellule Genre')], max_length=100, verbose_name='Direction')),
                ('post_occupe', models.CharField(max_length=100, verbose_name='Poste Occupé')),
                ('autre_tel', models.CharField(max_length=9, verbose_name='Autre Numéro')),
                ('utilisateur_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Utilisateur', to='utilisateur.utilisateur')),
            ],
        ),
    ]
