# Generated by Django 3.2.10 on 2021-12-26 18:42

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='auth.user')),
                ('utilisateur_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email_institutionnel', models.EmailField(max_length=100, unique=True, verbose_name='Email Institutionnel')),
                ('sexe', models.CharField(choices=[('m', 'Masculin'), ('f', 'Féminin')], max_length=100)),
                ('tel1', models.CharField(max_length=9, unique=True, verbose_name='Numéro Téléphone')),
                ('direction', models.CharField(choices=[('DAGE', 'DAGE'), ('DFPT', 'DFPT'), ('PEJA', 'PEJA'), ('CI', 'Cellule Informatique'), ('CG', 'Cellule Genre')], max_length=100, verbose_name='Direction')),
                ('post_occupe', models.CharField(max_length=100, verbose_name='Poste Occupé')),
                ('autre_tel', models.CharField(max_length=9, verbose_name='Autre Numéro')),
                ('is_admin', models.BooleanField(default='false', verbose_name='Etat Compte')),
                ('role', models.CharField(choices=[('AS', 'Admin Secondaire'), ('CP', 'Comptable Principale'), ('CS', 'Comptable Secondaire')], max_length=100, verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Utilisateur',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
