# Generated by Django 3.2.10 on 2021-12-26 19:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateur', '0001_initial'),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('attribution_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nbr_ticket', models.IntegerField(verbose_name='Nombre de Tickets Recus :')),
                ('current_date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 26, 19, 48, 28, 192485), verbose_name='Date Attribution')),
                ('date_rendez_vous', models.DateTimeField(verbose_name='Date Rendez-vous')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agents', verbose_name='Agents')),
                ('utilisateur_at_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.utilisateur', verbose_name='Utilisateur')),
            ],
        ),
    ]
